dir=0
credit[0]="DENNATON"
credit[1]="DENNIS & JONATAN"
credit[2]="DENNIS & JONATAN"
credit[3]="JONATAN SODERSTROM"
credit[4]="DENNIS WEDIN"
credit[5]="JONATAN SODERSTROM"
title[0]="A Game By"
title[1]="Game Design By"
title[2]="Story By"
title[3]="Programming By"
title[4]="Graphics By"
title[5]="Additional Graphics by"
current=0
textx=__view_get( e__VW.WView, 0 )*0.75
next=0
whitealpha=0
alarm[0]=300
