surf1=surface_create(room_width+32,room_height+100)
surface_set_target(surf1)
draw_clear_alpha(c_black,0)
surface_reset_target()
surf2=surface_create(room_width+32,room_height+100)
surface_set_target(surf2)
draw_clear_alpha(c_black,0)
surface_reset_target()
surf3=surface_create(room_width,room_height)
surface_set_target(surf3) 
draw_clear_alpha(c_black,0)
surface_reset_target()
dir=0
index1=0
index2=22
start_y=0
alarm[0]=240
myx=0
fade=0
c_amount=0
camount=0
wait=40
drops=0
if global.title="EXECUTION" blood=1 else blood=0
reload=16
